language: julia
os:
    - linux
julia:
    - nightly
    - 0.4
    - 0.3
notifications:
    email: false
before_install:
    - sudo apt-add-repository -y ppa:leo.robol/mpsolve
    - sudo apt-get update -qq
    - sudo apt-get install -y libmps3
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - if [ -f test/runtests.jl ]; then julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.test("MPSolve", coverage=false)'; fi
