language: julia
os:
    - linux
julia:
    - nightly
    - 1.3
notifications:
    email: false
before_install:
    - sudo apt-add-repository -y ppa:leo.robol/mpsolve
    - sudo apt-get update -qq
    - sudo apt-get install -y libmps3-dev
script:
 - julia --color=yes -e 'using Pkg; Pkg.test(coverage=false)'
