language: julia

os:
    - linux
    - osx
    - windows

arch:
  - amd64
  - arm64

julia:
    - nightly
    - 1.3
    - 1.4
    - 1.5

notifications:
    email: false

script:
 - julia --color=yes -e 'using Pkg; Pkg.test(; coverage=true)';

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage;
              Coveralls.submit(Coveralls.process_folder())'
