name = "MPSolve"
uuid = "9b0ab244-28a7-517c-931e-75c4e3199a6c"
authors = ["Leonardo Robol <leo@robol.it>", "Mikhail Kagalenko <kagalenko.m.b@rsreu.ru"]
version = "0.9.9"

[deps]
MPSolve_jll = "184ad7ad-f978-5c9a-833c-fb4ab31fd3fb"

[compat]
julia = "1.3"
